# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: "building docker image"
          command: docker build -t enjoydevops:$CIRCLE_BRANCH-$CIRCLE_SHA1 .

  test:
    machine:
      image: ubuntu-2004:current
    steps:
      - run: |
          echo testing
          docker images
      - run: echo deploying

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  ci-build:
    jobs:
      - build
      - test:
          requires:
          - build