# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    machine:
      image: ubuntu:lts
    steps:
      - checkout
      - run: |
          echo "building docker image"
          docker build -t enjoydevops .
  test:
    steps:
      - run: |
          echo testing
          docker images
  deploy:
    steps:
      - run: echo deploying

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
    jobs:
      - build
      - test
      - deploy
 